# I was bored lol

DOWNLOAD_TEXTS = [
    "Fetching...",
    "Retrieving...",
    "Rawr...!",
    "Downloading...",
    "Working on it...",
    "Almost there...",
    "Hang tight...",
    "This file big as hell bro...",
    "Just a sec...",
    "Hold on...",
    "Beep boop...",
    "Computer noises...",
    "Sprett's fursona is a leaf-nosed bat...",
    "Stealing your data...",
    "Downloading the entire internet...",
    "What are you looking for? There's nothing here...",
    "Fetching the fetch...",
    "Downloading the download...",
    "This is taking longer than expected...",
    "This button gets more colorful every time you click it...",
    "How's your day going? Mine's going well, thanks for asking...",
    "Happy birthday...! If it's not your birthday, happy unbirthday...!",
    "Downloading the entire internet...",
    "Make sure to stay hydrated...",
    "Downloading more RAM...",
    "Bro is getting rate limited...",
    "I love downloading things...!",
    "Consulting the ancient scrolls...",
    "Hacking into the mainframe or something idk...",
    "Please do not turn off your computer (just kidding, do whatever)...",
    "Be patient, this is a very large file (or maybe not, idk)...",
    "Generating random excuses for why this is slow...",
    "Happy multithreading monday...!",
    "What's your favorite color? Mine's purple...",
    "Hello, world...!",
    "You're pretty cool, you know that? Just thought I'd let you know...",
    "Dudes be downloading anything...",
    "Is this a music album or a video playlist? I can't tell...!",
    "Sprett is a cool guy, you should check out his stuff...!",
    "Deadly Operating System is never gonna be released...",
    "Merry Christmas...!",
    "Happy New Year...!",
    "Happy Halloween...!",
    "Happy Easter...!",
    "Happy Thanksgiving...!",
    "Happy Valentine's Day...!",
    "Happy St. Patrick's Day...!",
    "Happy April Fool's Day! April Fool's...!",
    "Happy pride month...!",
    "Happy International Women's Day...!",
    "Happy International Men's Day...!",
    "Happy International Day of Awesomeness...!",
    "Happy International Day of Happiness...!",
    "Happy International Day of Friendship...!",
    "I'm running out of ideas for these messages, but I hope you're having a good day...!",
    "Downloading the entire internet... again...",
    "Downloading the entire internet... again... and again...",
    "Downloading the entire internet... again... and again... and again...",
    "Downloading the entire internet... again... and again... and again... and again...",
    "Yay! You're downloading stuff...!",
    "How many downloads have you done today? I hope it's a lot...!",
    "Tell me a joke while you wait... I love jokes...!",
    "Tell your friends about Fetch...",
    "Tell your enemies about Fetch... I don't care, just tell people about Fetch...!",
    "Fetch fetches files...!",
    "Fetch is fetching files...!",
    "Good morning...! Good evening...! Good night...! Good whatever time it is for you...!",
    "Bats are the only mammals capable of true, sustained flight...!",
    "The leaf-nosed bat's nose is shaped like a leaf to help it echolocate...!",
    "The sword-nosed bat has a tongue extending up to half its body length...!"
]